name: Example Push Action
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://osrelease.download.prss.microsoft.com/pr/download/Mariner-2.0-x86_64.iso
          sudo apt-get install isoinfo p7zip-full p7zip-rar
          mkdir outputfortext
          isoinfo -i  Mariner-2.0-x86_64.iso -l > outputfortext/Output.txt

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: outputfortext/



